DROP PROCEDURE IF EXISTS PR;
DELIMITER $$
CREATE PROCEDURE PR(A INT, B INT)
BEGIN
	DECLARE M INT;
	SET M = A * B;
	IF M > 100 THEN
		SELECT 'PRODUCT GREATER THAN 100';
	ELSEIF M = 100 THEN
		SELECT 'PRODUCT IS EQUAL TO 100';
	ELSE
		SELECT 'PRODUCT LESS THAN 100';
	END IF;
END;
$$
DELIMITER ;

--SOURCE D:/AC/sunbeamdata/dbt/Day08/PSM95.SQL