DROP PROCEDURE IF EXISTS CONV;
DELIMITER $$
CREATE PROCEDURE CONV(n INT)
BEGIN
	DECLARE Y INT;
	DECLARE F INT;
    DECLARE R INT;
	SET Y = n/36;
	SET R = n % 36;
	SET F = n/12;
	SET R = n % 12;
	SELECT Y AS YARD, F AS FOOT, R AS INCHES;
END;
$$
DELIMITER ;