DROP PROCEDURE IF EXISTS JOB;
DELIMITER $$
CREATE PROCEDURE JOB(IN ID CHAR(20), OUT TITLE CHAR(20), OUT MIN INT, OUT MAX INT)
BEGIN
    SELECT JOB_TITLE, MIN_SALARY, MAX_SALARY INTO TITLE, MIN, MAX 
    FROM JOBS WHERE JOB_ID = ID;
END;
$$
DELIMITER ;


/*

SET @res = 0;
SET @res1 = 0;
SET @res2 = 0;
call JOB('AD_PRES', @res, @res1, @res2);
SELECT @res, @res1, @res2;

SOURCE D:/AC/sunbeamdata/dbt/Day08/PSM95.SQL

*/
